name: Gradle publishing

on:
  push:
    branches:
      - 'master'
  workflow_call:
    secrets:
      GPG_SECRET:
        required: true
      GPG_PASSWORD:
        required: true

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

#      - name: Setup Cross
#        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        env:
          SIGN_ENABLED: true
        run: |
          echo -e "${{ secrets.GPG_SECRET }}" | gpg --batch --import
          ./gradlew build publishJavaPublicationToOSSRHRepository publishReleasePublicationToOSSRHRepository \
            -Psigning.gnupg.keyName=${{ secrets.GPG_ID }} -Psigning.gnupg.passphrase=${{ secrets.GPG_PASSWORD }} \
            -POSSRHUsername=${{ secrets.OSSRH_LOGIN }} -POSSRHPassword=${{ secrets.OSSRH_PASSWORD }}