name: Gradle publishing

env:
  SIGN_ENABLED: true
  SIGN_KEY: ${{ secrets.GPG_SECRET }}
  SIGN_PASSWORD: ${{ secrets.GPG_PASSWORD }}

on:
  push:
    branches:
      - 'master'

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew build